### ISSUE TITLE
ModuleNotFoundError: No module named 'unsup_vvs.network_training.models.simclr'

### ISSUE THREAD

**Issue by RylanSchaeffer** [brain-score/candidate_models#88]
I'm trying to use `candidate_models` with Brain Score, but I received the following error:

```
  File "python3.7/site-packages/candidate_models/base_models/unsupervised_vvs/__init__.py", line 77, in __call__
    cfg_kwargs=self.CFG_KWARGS.get(identifier, {}))
  File "python3.7/site-packages/candidate_models/base_models/unsupervised_vvs/__init__.py", line 133, in __get_tf_model
    model_type=model_type, cfg_kwargs=cfg_kwargs)
  File "python3.7/site-packages/candidate_models/base_models/unsupervised_vvs/__init__.py", line 157, in _build_model_ending_points
    **cfg_kwargs)
  File "python3.7/site-packages/unsup_vvs/neural_fit/cleaned_network_builder.py", line 189, in get_network_outputs
    ending_points = get_simclr_ending_points(inputs)
  File "python3.7/site-packages/unsup_vvs/neural_fit/cleaned_network_builder.py", line 22, in get_simclr_ending_points
    from unsup_vvs.network_training.models.simclr import resnet
ModuleNotFoundError: No module named 'unsup_vvs.network_training.models.simclr'
```

**Comment by RylanSchaeffer** [comment]
I'm going to try to find the cause, but I thought it best to open an issue in the interim and maybe then post my solution.

**Comment by RylanSchaeffer** [comment]
I can import most of the path

```
>>> import unsup_vvs
>>> import unsup_vvs.network_training
>>> import unsup_vvs.network_training.models
>>> import unsup_vvs.network_training.models.simclr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'unsup_vvs.network_training.models.simclr'
>>> 
```

**Comment by RylanSchaeffer** [comment]
Ah! Found the issue! `setup.py` pulls the `bs_latest` branch (See: https://github.com/brain-score/candidate_models/blob/master/setup.py#L29), which is 4 commits behind `master` (https://github.com/neuroailab/unsup_vvs/tree/bs_latest) and it indeed lacks the `simclr` subdirectory.

@mschrimpf @chengxuz , what's your recommended solution? Is it alright to use the `master` branch, or is there a reason why the `bs_latest` branch is specified?

**Comment by RylanSchaeffer** [comment]
Related to this PR https://github.com/brain-score/candidate_models/pull/78
